name: bonsai
dependencies:
  - python=3.7
  - pip=19.1.1
  - jupyter=1.0.0
  - matplotlib=3.0.3
  - seaborn=0.9.0
  - plotly=3.10.0
  - scipy=1.3.0
  - pandas=1.2.2
  - numpy=1.19.2
  - bcrypt=3.2.0
  - pip:
      - microsoft-bonsai-api==0.1.2
      - msal==1.4.3
      - bonsai-cli==1.0.10
      - azure-cli==2.24.0
      - cufflinks==0.16
      - vpython==7.6.0
      - pyglet==1.5.0
      - jinja2==2.11.2
      - python-dotenv==0.13.0
      - typer==0.2.1
      - Kqlmagic==0.1.113.post1
      - pytest==6.0.1